version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: gaifut/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    image: gaifut/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      - ./frontend/:app/result_build/
  nginx:
    image: gaifut/foodgram_nginx
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 11000:80
    volumes:
      - static:/static
      - media:/app/media
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/

