# Generated by Django 3.2.16 on 2024-02-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
