# Generated by Django 3.2.16 on 2024-02-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
