# Generated by Django 3.2.16 on 2024-03-03 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше1'), django.core.validators.MaxValueValidator(32000, message='Значение не может быть больше32000')], verbose_name='количество'),
        ),
    ]
