# Generated by Django 3.2.16 on 2024-02-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribe',
        ),
    ]
