# Generated by Django 3.2.16 on 2024-03-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0003_recipe_added_to_shopping_cart_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='added_to_shopping_cart_by',
        ),
    ]
