# Generated by Django 3.2.16 on 2024-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0005_ingredientrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
