# Generated by Django 3.2.16 on 2024-03-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0005_userrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
