# Generated by Django 3.2.16 on 2024-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0005_auto_20240221_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
