# Generated by Django 3.2.16 on 2024-03-02 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_logic', '0006_delete_userrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='added_to_shopping_cart_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
