# Generated by Django 3.2.16 on 2024-03-02 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_logic', '0007_recipe_added_to_shopping_cart_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='recipe_favorited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='added_to_shopping_cart_by',
            field=models.ManyToManyField(blank=True, related_name='recipe_added_to_shopping_cart_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
