# Generated by Django 3.2.16 on 2024-02-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0008_alter_ingredientrecipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_recipe', to='business_logic.recipe'),
        ),
        migrations.DeleteModel(
            name='TagRecipe',
        ),
    ]
