# Generated by Django 3.2.16 on 2024-02-19 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0010_auto_20240219_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
