# Generated by Django 3.2.16 on 2024-02-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0012_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
